### ISSUE TITLE
怎么把src/main.js等文件修改成src/main.ts的

### ISSUE THREAD

**Issue by Undertone0809** [imaxing/uni-app-project-template#1]
我想知道uniapp下的main.js等文件是怎么修改成ts的呀，直接改了语言uniapp也可以识别main的吗？还是说做了一些其他的修改。

**Comment by imaxing** [comment]
抱歉
此仓库是从[uni-app-vue2-tailwind-vscode-template](https://github.com/sonofmagic/uni-app-vue2-tailwind-vscode-template)fork的
具体配置没有了解, 可咨询 [ice breaker](https://github.com/sonofmagic)
